# Travis CI script
language: c

os:
- linux
- osx

sudo: false

services:
- docker

env:
- BUILD_TYPE=default

addons:
  apt:
    packages:
    - uuid-dev
    - valgrind
    - git

before_install:
- if [ $TRAVIS_OS_NAME == "osx" ] ; then brew update; brew install binutils valgrind ; fi

# Build and check this project according to the BUILD_TYPE
script: ./ci_build.sh

